### ISSUE TITLE
Addition of minimally viable secure software design design controls

### ISSUE THREAD

**Issue by 6mile** [vendorsec/mvsp#10]
I believe we are missing a piece to the MVSP checklist and that's several checklist items that involve secure software development processes.  I believe the best place to add these is in section 2 under the "Application Design Controls" heading. The five additional items that I can think of now are:
1. Continuous integration and delivery processes should be required to automate the implementation of security and other tests as well as to provide an audit capture point for all changes that are pushed to prod
2. Sofware source code scanning tools to stop the developer from embedding credentials and secrets in code
3. Software source code scanning tools to stop the developer from embedding vulnerable third party or open-source libraries in code
4. .gitignore files should be required so that sensitive data and potentially malicious files are not allowed into source code repositories
5. Pull requests or merge requests should be enforced and so that all changes to environments are seen by at least one additional developer whose job it is to enforce security requirements for all code changes

All 5 of these suggestions have been vetted (in my head) against the simple test laid out in the MVSP contributing guidelines that I'm including here: "Could I consider a vendor secure if they did not comply with the control I am adding?"  To my mind, no vendor could be considered secure if they didn't enforce all five of these suggestions.  I mean, if we are suggesting that CSP is a requirement, which less than 10% of websites currently now use, should we not also require the use of continuous integration and associated security tests?  .gitignore files and git hook scripts should be required for all software engineers as these stop potential data leaks.

**Comment by ChrisJohnRiley** [comment]
Many thanks for the input and extensive thoughts on this.

We've had some alignment discussions with the SLSA team (https://slsa.dev/) which attempts to deal with some of the aspects you've touched on here (CI and code review).

I believe there is room for some of these recommendations in future iterations of MVSP, alongside considerations such as unit testing, however we need to consider that some (point 4) are technology/vendor specific.

We'll ensure to review this alongside the future control review.

> ...if we are suggesting that CSP is a requirement, which less than 10% of websites currently now use...
https://chromestatus.com/metrics/feature/timeline/popularity/15 shows an average of ~46% (I understand this is a limited view on the landscape).

**Comment by ChrisJohnRiley** [comment]
Looping back on this as we're closing out areas that have been reviewed and considered for inclusion into MVSP 2022 control refresh. We plan to incorporate a control 3.5 Build process that introduces SLSA level 1 (to keep with the theme of minimums). This will go-live once we have final sign-offs. Hopefully this begins to address the requirements you mentioned.
