### ISSUE TITLE
Have you considered any integration with the SLSA framework?

### ISSUE THREAD

**Issue by kimsterv** [vendorsec/mvsp#16]
[SLSA](slsa.dev) is a leveling framework for software supply chain integrity, with a big emphasis on provenance (understanding how an artifact was built). SLSA has some overlap with mvsp in terms of requirements. At the minimum, it seems like mvsp could benefit from a requirement around the provenance of the B2B software being delivered so producers of software can better assert as to what they are providing to their consumers, and consumers can verify they've received what was intended. One way to implement an improvement here is to require producers of the software to cryptographically sign the final package/binary. The [sigstore](sigstore.dev) project would be an easy way to implement the signing/verification flow. Thoughts?

**Comment by ChrisJohnRiley** [comment]
Hi Kim,

Thanks for reaching out on this. We have had discussions with the team responsible for SLSA to examine where MVSP and SLSA may align and overlap. As part of the annual review of controls we will be considering if inclusion of SLSA (perhaps tier 1) fits with minimum criteria needed to include this in MVSP.

**Comment by ChrisJohnRiley** [comment]
Hi Kim,

Looping back on this as we're closing out areas that have been reviewed and considered for inclusion into MVSP 2022 control refresh. We plan to incorporate a control 3.5 _Build process_ that introduces SLSA level 1 (to keep with the theme of minimums). This will go-live once we have final sign-offs. Hopefully this meets the requirements you mentioned.
