### ISSUE TITLE
Doubt in the Package.json file while installing.

### ISSUE THREAD

**Issue by SwathiSam31** [vendorsec/mvsp#21]
When I try yo install the package, I got an error like

error code EUNSUPPORTEDPROTOCOL
error Unsupported URL Type "workspace:": workspace:*

Which is generated by the Lines in the package.json 

"@mvsp/doc": "workspace:*",
"@mvsp/parcel-namer-mvsp": "workspace:*",
"@mvsp/parcel-resolver-mvsp": "workspace:*",

May I know how to resolve this error?

Nodejs and npm versions:

verbose node v14.19.1
verbose npm  v8.5.5

**Comment by touzoku** [comment]
@SwathiSam31, you need to use the [pnpm package manager](https://pnpm.io).
