### ISSUE TITLE
How does this relate to SLSA?

### ISSUE THREAD

**Issue by rjb4standards** [vendorsec/mvsp#7]
I've read Royal's 10/27 blog post, but I'm unable to determine how or if MVSP relates to SLSA. Any insights you can offer would be appreciated. Today, SAG-PM (TM) looks for a URL to a SLSA/in-toto package in a Vendor Supplied Response File in an element called SDLCEvidenceDataURL, which it downloads as part of a risk assessment. I'm trying to determine if I need to add  a separate element for MVSP in the open source Vendor Response File schema: https://github.com/rjb4standards/REA-Products/blob/master/SAGVendorSchema.xsd or if MVSP data will be incorporated into a SLSA package.

Thanks for you insights. 

Dick Brooks
dick@reliableenergyanalytics.com
Reliable Energy Analytics, LLC
Co-Founder and Lead Software Engineer for SAG-PM (TM)

**Comment by ChrisJohnRiley** [comment]
Hi Dick,

Many thanks for reaching out on this.

SLSA is intended to be a framework for evaluating the integrity of a software supply chain, while MVSP is a framework for evaluating the security of a business as a whole. We're exploring how we can better align SLSA and MVSP moving forwards, however at this time the two are designed to address different sets of requirements.

**Comment by rjb4standards** [comment]
Hi Chris,
Thanks for your response. Based on your description, MVSP seems to be covered by an existing element in the Vendor Response File called CyberSecPolicyURL. I'm interested in learning more about how to integrate MVSP processing into SAG-PM using the MVSP materials covered in the CyberSecPolicyURL element of a Vendor Response File.

Thanks.
