### ISSUE TITLE
q: Does the wiki / FAQ contain information on how to publish this site for evaluation ?

### ISSUE THREAD

**Issue by 2ndRecon** [vendorsec/mvsp#9]
Probably a dense question, I presume there's a simple answer as to how to publish this on an internal QA web instance to poke around and try it out ?

**Comment by touzoku** [comment]
@2ndRecon the website is built using [aws-cdk](https://docs.aws.amazon.com/cdk/latest/guide/home.html). You can deploy a fully functioning copy of this website by running `yarn install` and `yarn workspace @mvsp/aws run cdk deploy --all`. The running cost of it is around $0 to $1.1 a month depending on your AWS free tier usage.

You would have to change [ZONE_NAME](https://github.com/vendorsec/mvsp/blob/4a6ad275c029c7bfb3c7c539abb419c2efc711a7/packages/aws/deploy.ts#L10) to your DNS zone and [hostnames for the website](https://github.com/vendorsec/mvsp/blob/4a6ad275c029c7bfb3c7c539abb419c2efc711a7/packages/aws/deploy.ts#L23).

If you just want to run a website on your localhost, then run `yarn dev` and it will start on port 5000.
